#! /usr/bin/python
import os 
BLACK = "\033[0;30m"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
BROWN = "\033[0;33m"
BLUE = "\033[0;34m"
PURPLE = "\033[0;35m"
CYAN = "\033[0;36m"
LIGHT_GRAY = "\033[0;37m"
DARK_GRAY = "\033[1;30m"
LIGHT_RED = "\033[1;31m"
LIGHT_GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
LIGHT_BLUE = "\033[1;34m"
LIGHT_PURPLE = "\033[1;35m"
LIGHT_CYAN = "\033[1;36m"
LIGHT_WHITE = "\033[1;37m"
BOLD = "\033[1m"
FAINT = "\033[2m"
ITALIC = "\033[3m"
UNDERLINE = "\033[4m"
BLINK = "\033[5m"
NEGATIVE = "\033[7m"
CROSSED = "\033[9m"
END = "\033[0m"
# user_info = os.getuid()
# if user_info != 0:
#     print(f"{LIGHT_RED}run as root{END}")
#     exit()
banner = CYAN+"""

                                                                                                    
                                                                                                    
                                                                                                                                                      
                       ?&&~                               ?&&^              ^&&J    G&&.                                                              
                       Y@@7                               !BB:              ~@@G    YBG                                                               
                       Y@@7                                                 ~@@P                                                                      
       !P&&@@&&G7.     Y@@J!B&&@&&5^      .J#&&@&&&P~     7##^     :Y#&@&&#77@@P    5#B      !P&&&@@@&B?     .B&!:5&&@@@#Y.                           
     7@@@Y^::^J&@@J    Y@@@@Y^::~G@@B.   !@@G~:::~P@@#    Y@@!    G@@G!::^J&@@@P    &@@.   ^@@@?^:::~P@@&.   .@@@@G!^:^J@@@~                          
    7@@B        5@@5   Y@@#       ^@@#   B@@~      ^?7    Y@@!   B@@!       B@@P    #@@.   ?GP.       P@@!   .@@@^      ^@@#                          
    &@@.         @@@.  Y@@^        G@@^  .#@@@&B5?^.      Y@@!  :@@#        :@@P    #@@.      .^~!?YPB@@@7   .@@#       .@@#                          
    &@@.         &@@.  Y@@:        P@@!    .~YG#@@@@@G.   Y@@!  ^@@B        .@@P    #@@.   :G@@@&&BG57B@@7   .@@#       .@@#                          
    G@@!        :@@&   Y@@?        &@@.  :^.      .J@@&   Y@@!   @@@.       ~@@P    #@@.  ^@@&^       G@@7   .@@#       .@@#                          
    .&@@?      !@@@:   Y@@@?     :#@@!   &@@!      ~@@B   Y@@!   ^@@&^     !@@@P    #@@.  7@@#      .5@@@7   .@@#       .@@#                          
      ?&@@&BB#@@&Y.    Y@@G&@#BB&@@G.     P@@@#BB#&@&Y    Y@@!    .P@@&#B#@@P@@G    #@@.   J@@@BGPB#&BY@@B   .@@#       .@@&                          
        .~7JJ?~.       .^^  :7JJ7^          :!?JJ?~.      .^^        :!JJ7^  ^^.    :^^      :!JJ?!:   :^^    ^^:        ^^:                                                                                                      
                   -----------------------welcome to obsidian tool-----------------------
                                                                                                    
                                                                                                                                                                        
 """+END
print(banner+"\n\n")
print(LIGHT_CYAN+"[1] = create_payload+listen")
print("[2] = reverse shell code")
print("[3] = gobuster_scan")
print("[4] = wordpress_crack")
print("[5] = web login brute force")
print("[6] = cgi-bin exploit")
print("[7] = Guess passwords")
print("[8] = hash cracker(john)")
print("[help] = help mode"+END)

while True : 

    ask = input(f"\n┌──({LIGHT_RED}obsidian{END}㉿{LIGHT_RED}obsidian-tools{END})-[----{YELLOW}menu{END}----]\n└─{LIGHT_RED}#{END} ")
    #-----------------------------------------------
    if ask != "1" and ask != "2" and ask != "3" and ask != "4" and ask != "5" and ask != "6" and ask != "help" and ask != "7" and ask != "8" and ask != "list" and ask != "clear" and ask != "" and ask != "\n" and ask != "exit" and ask != "banner" :
        print(ask+": "+LIGHT_RED+"command not found"+END)
        #-----------------------------------------------
    if ask == "1" : 
        os.system("python /root/obsidian-tools/create_reverse_shell.py")
    if ask == "2" : 
        os.system("python /root/obsidian-tools/reverse_shell_code.py")
    if ask == "3" : 
        os.system("python /root/obsidian-tools/simscan.py")
    if ask == "4" : 
        os.system("python /root/obsidian-tools/wordpress_crack.py")
    if ask == "5" : 
        os.system("python /root/obsidian-tools/brute_force.py")
    if ask == "6" : 
        os.system("python /root/obsidian-tools/cgi-bin.py")
    if ask == "7" : 
        os.system("python /root/obsidian-tools/Guess_passwords.py")
    if ask == "8" : 
        os.system("python /root/obsidian-tools/hashcracker.py")
    #--command
#-----------------------------------------------
    if ask == "help" : 
        print(LIGHT_CYAN+"    These commands can be used")
        print("       [help] for help ")
        print("   [list] for list command")
        print("   [banner] for print banner")
        print("[clear] for clear the terminal screen"+END)
#-----------------------------------------------
    if ask == "clear" :
        os.system("clear")
#-----------------------------------------------e
    if ask == "list" :
        print(LIGHT_CYAN+"[1] = create_payload+listen")
        print("[2] = reverse shell code")
        print("[3] = gobuster_scan")
        print("[4] = wordpress_crack")
        print("[5] = web login brute force")
        print("[6] = cgi-bin exploit")
        print("[7] = Guess passwords")
        print("[8] = hash cracker(john)")
        print("[help] = help mode"+END)
#-----------------------------------------------
    if ask == "banner" :
        print(banner)
#-----------------------------------------------
    if ask == "exit" :
        exit()
